apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster
  region: ca-central-1

nodeGroups:
  - name: linux-nodes
    instanceType: t2.micro
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 80
    tags:
      - key: "project"
      - value: "github_action"
    ssh:
      allow: true