apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: gitHub-action
  region: ca-central-1
  version: "1.24"

nodeGroups:
  - name: linux-nodes
    instanceType: t2.micro
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 80
    tags:
      "environment": "dev"
      "project": "github_action"
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/id_ec2.pub