apiVersion: v1
kind: Service
metadata:
  name: github-action-service
spec:
  selector:
    app: github-action-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer